services:
  - type: web
    name: fastapi-app
    env: python
    pythonVersion: "3.11"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
    plan: free
    envVars:
      - key: REDIS_URL
        value: redis://redis-service:6379
      - fromGroup: google-oauth
      - fromGroup: supabase
      - fromGroup: auth
      - key: ENVIRONMENT
        value: production
      - key: RUN_SCHEDULER
        value: "true"   # Scheduler will run in this single worker

  - type: worker
    name: dramatiq-worker
    env: python
    pythonVersion: "3.11"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m dramatiq jobs --watch . --threads 4
    plan: free
    envVars:
      - key: REDIS_URL
        value: redis://redis-service:6379
      - fromGroup: supabase
      - key: ENVIRONMENT
        value: production

  - type: redis
    name: redis-service
    plan: free
