services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 5000
    plan: free
    envVars:
      - key: REDIS_URL
        value: redis://redis-service:6379

  - type: worker
    name: dramatiq-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: dramatiq app.tasks --watch app
    plan: free
    envVars:
      - key: REDIS_URL
        value: redis://redis-service:6379

  - type: private-service
    name: redis-service
    env: docker
    dockerfilePath: redis/Dockerfile
    plan: free
